version: "3"
services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - data:/data

  client1:
    build: ./client
    ports:
      - "4000:4000"
    depends_on:
      - redis

volumes:
  data: {}
