version: "3"
services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    volumes:
      - data:/data

  publisher1:
    build: ./publisher
    env_file:
      - ./publisher/docker.env
    ports:
      - "4000:4000"
    depends_on:
      - redis

volumes:
  data: {}
